title: Edz Website
author: Edwin Chao
email: echao2@ebnet.org
description: 
Enjoy reading up about me

# social links
twitter_username: aidaween_
github_username:  echao2

show_excerpts: true 
theme: minima
